version: "3.3"
    
services:
  db:
    image: mariadb:10.4
    container_name: db_${PROJECT_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - db_network
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: db_${PROJECT_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PASS}
      PUID: ${HOST_USER_ID}
      PGID: ${HOST_GROUP_ID}
    labels:
      # Disable Traefik
      - traefik.enable=false
    
  wp_app:
    depends_on:
      - db
    build:
      context: ./
      args:
        SMTP_SERVER: ${SMTP_SERVER}
        AUTH_USER: ${AUTH_USER}
        AUTH_PASS: ${AUTH_PASS}
    container_name: wp_${PROJECT_NAME}
    volumes:
      - html_data:/var/www/html
    networks:
      - db_network
    restart: always
    environment:
      PUID: ${HOST_USER_ID}
      PGID: ${HOST_GROUP_ID}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PASS}
      WORDPRESS_DB_NAME: db_${PROJECT_NAME}
    ports:
      - ${APP_PORT}:80
    labels:
      # Non-TLS routing.
      # Comment this out when moving to TLS
      - traefik.http.routers.app_${PROJECT_NAME}.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.app_${PROJECT_NAME}.entrypoints=web
      
      # Automatic TLS
      # # Uncomment below for TLS
      # - traefik.http.routers.app_${PROJECT_NAME}.rule=Host(`${HOSTNAME}`)
      # - traefik.http.routers.app_${PROJECT_NAME}.entrypoints=websecure
      # - traefik.http.routers.app_${PROJECT_NAME}.tls.certresolver=myresolver
      # # Seperate Router for https redirect
      # - traefik.http.routers.app_${PROJECT_NAME}-insec.rule=Host(`${HOSTNAME}`)
      # - traefik.http.routers.app_${PROJECT_NAME}-insec.entrypoints=web
      # - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      # - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # - traefik.http.routers.app_${PROJECT_NAME}-insec.middlewares=https-redirect@docker

      # Override default middleware name, and redirect to port 80 in TLS
      - traefik.http.services.app_${PROJECT_NAME}.loadbalancer.server.port=80

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma_${PROJECT_NAME}
    networks:
      - db_network
    environment:
      PMA_HOST: db
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      PUID: ${HOST_USER_ID}
      PGID: ${HOST_GROUP_ID} 
    restart: always
    ports:
      - ${PMA_PORT}:80
    labels:
      # TODO Find way to serve phpmyadmin on /phpmyadmin path. Container currently listens on "/". So results in 404...
      - traefik.http.routers.pma_${PROJECT_NAME}.entrypoints=web
      - traefik.http.routers.pma_${PROJECT_NAME}.rule=Host(`${HOSTNAME}`) && PathPrefix(`/phpmyadmin`)

volumes:
  # A volume for future use by a backup service
  db_data: {}

  # HTML root dir
  html_data:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/src/html

networks:
  db_network: {}
